version: '3'
services:
  database:
    image: tinigdb
    build:
      context: .
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

      - GDB_PASSWORD
      - GDB_BACKUP_FILE
    ports:
      - 9991:5432
    volumes:
      - database_data

volumes:
  database_data:
    external:
      name: tinigdb-database_data
